version: '3.8'

services:

  # Veritabanı
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: deneme
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 112131
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d deneme"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Backend (FastAPI)
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    environment:
      DATABASE_URL: postgresql://user:112131@db:5432/deneme
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
    restart: unless-stopped

  # Frontend (React)
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules 
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true 
    restart: unless-stopped
  

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped


volumes:
  postgres_data: